CREATE TABLE IF NOT EXISTS POSTS (
    NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NULL DEFAULT NULL,
    VIEWS INT DEFAULT 0
);
